services:
  odata-manager-app:
    restart: on-failure
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE
      - MONGO_SYNC_CONNECTION_STR
      - MONGO_DATABASE
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_URL
      - ENABLE_DEBUG=false
      - LOOKUP_TYPE
      - CERT_REPORT_FILENAME
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "development.jv79a9p.mongodb.net:89.192.213.96"
      - "ac-uyghdrj-shard-00-00.jv79a9p.mongodb.net:89.192.205.184"
      - "ac-uyghdrj-shard-00-01.jv79a9p.mongodb.net:89.192.213.96"
      - "ac-uyghdrj-shard-00-02.jv79a9p.mongodb.net:89.192.206.237"
    volumes:
      - ./build/libs:/usr/local/tomcat/webapps
    depends_on:
      - mysql-db
      - mongo-db

  mysql-db:
    image: mariadb:latest
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=${MYSQL_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10


# add dummydata
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-reso}
      CERT_REPORT_FILENAME: RESODataDictionary-1.7.metadata-report.json
      ATLAS_DATAFILL_URI: ${ATLAS_DATAFILL_URI}
    volumes:
      - "./certification-reports/RESODataDictionary-1.7.metadata-report.json:/RESODataDictionary-1.7.metadata-report.json"
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Development Tools
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo-db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_SYNC_CONNECTION_STR}
      ME_CONFIG_BASICAUTH: false

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8082:80"

volumes:
  mysql_data:
  mongo_data: